services:
  - type: web
    name: edumorph-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: ML_SERVICE_URL
        value: https://edumorph-ml-service.onrender.com
      - key: MCP_SERVICE_URL
        value: https://edumorph-mcp-service.onrender.com
      - key: LOG_LEVEL
        value: production
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: OPENAI_TEMPERATURE
        value: 0.7
      - key: FRONTEND_URL
        value: https://edumorph-frontend.vercel.app